### ISSUE TITLE
Validate OSX builds

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nb_conda_kernels-feedstock#10]
Looks like the py3.4/2.7 on OSX builds failed due to a race in the new build of tornado. Rekicked them, will see if that does the trick:
https://travis-ci.org/conda-forge/nb_conda_kernels-feedstock

**Comment by jakirkham** [comment]
They failed to upload or they built bad binaries?

**Comment by bollwyvl** [comment]
The tests failed, because they pulled tornado missing `singledispatch` and friends, so they didn't upload.

**Comment by bollwyvl** [comment]
Now they are up!
https://anaconda.org/conda-forge/nb_conda_kernels/files
