### ISSUE TITLE
noarch build no longer activates nb_conda_kernels on windows

### ISSUE THREAD

**Issue by mathause** [conda-forge/nb_conda_kernels-feedstock#51]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Installing the newest noarch build (`_3`) no longer activates nb_conda_kernels on windows. Therefore kernels are no longer found by jupyter.

To reproduce run the following on windows:

```bash
mamba create -n test_nb_conda_kernels nb_conda_kernels
# or the exact spec
# mamba create -n test_nb_conda_kernels nb_conda_kernels=2.3.1=pyhd8ed1ab_3

conda activate test_nb_conda_kernels

python -m nb_conda_kernels.install --status
```

Returns `Status: disabled`

**Comments**:

- the previous build activated nb_conda_kernels (see below)
- it still works on linux
- python 3.11 still uses the second build (and does therefore currently not have this problem)

```bash
mamba create -n test_nb_conda_kernels_build2 nb_conda_kernels=2.3.1=py310h5588dad_2

conda activate test_nb_conda_kernels_build2

python -m nb_conda_kernels.install --status
```
returns `Status: enabled`

**Workaround**

The workaround is to either manually install the older build, or enable it manually:

```bash
python -m nb_conda_kernels.install -v --enable
```

### Installed packages

```shell
let me know if you need this info
```

### Environment info

```shell
let me know if you need this info
```

**Comment by mathause** [comment]
Probably `.nb_conda_kernels-post-link.bat` is no longer called?

https://github.com/conda-forge/nb_conda_kernels-feedstock/blob/32a09efd4a8930662c6e1e569e737ff774acfc3a/recipe/bld.bat#L8

https://github.com/Anaconda-Platform/nb_conda_kernels/blob/d217629e5a91d294169149534f5d01aa250a47eb/conda-recipe/post-link.bat

**Comment by ocefpaf** [comment]
That is likely the reason. I thought that we addressed that but it seems that we did not. I'm OK reverting this back to "arch'ed" b/c I don't know a better OS agnostic way to do this. Do you want to send a PR to fit this? We can probably use the new OS-noarch option in conda-forge: https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-packages-with-os-specific-dependencies

That way it is still "python noarch" but it can use the scripts in all OSes.
